apiVersion: v1
kind: Service
metadata:
  name: nats-server-cluster
spec:
  ports:
  - name: client
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats
    nats_cluster: nats-server-cluster
  type: NodePort
