apiVersion: v1
kind: Service
metadata:
  name: gravity-nats-mgmt
spec:
  ports:
  - name: cluster
    port: 6222
    protocol: TCP
    targetPort: 6222
  - name: monitor
    port: 8222
    protocol: TCP
    targetPort: 8222
  selector:
    app: nats
    nats_cluster: gravity-nats
  type: ClusterIP
  clusterIP: None
