apiVersion: v1
kind: Service
metadata:
  name: nats-server-cluster-mgmt
spec:
  ports:
  - name: cluster
    port: 6222
    protocol: TCP
    targetPort: 6222
  selector:
    app: nats
    nats_cluster: nats-server-cluster
    nats_version: latest
  type: ClusterIP
