apiVersion: v1
kind: Service
metadata:
  name: gravity-nats
spec:
  ports:
  - name: client
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats
    nats_cluster: gravity-nats
  type: ClusterIP
