apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-server-cluster

spec:
  replicas: 3
  selector:
    matchLabels:
        app: nats
        nats_cluster: nats-server-cluster
        
  serviceName: nats-server-cluster-mgmt
  template:
    metadata:
      labels:
        app: nats
        nats_cluster: nats-server-cluster
    spec:
      containers:
      - name: nats-server
        command:
          - /nats-server
          - --routers=nats-server-cluster-mgmt:6222
        image: iamjhe/nats-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4222
          name: nats
          protocol: TCP
        - containerPort: 6222
          name: nats-mgmt
          protocol: TCP
