apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gravity-nats

spec:
  replicas: 3
  selector:
    matchLabels:
        app: nats
        nats_cluster: gravity-nats
        
  serviceName: gravity-nats-mgmt
  template:
    metadata:
      labels:
        app: nats
        nats_cluster: gravity-nats
    spec:
      containers:
      - name: nats-server
        command:
          - /nats-server
          - --routes=gravity-nats-0.gravity-nats-mgmt.default.svc.cluster.local:6222
          - --routes=gravity-nats-1.gravity-nats-mgmt.default.svc.cluster.local:6222
          - --routes=gravity-nats-2.gravity-nats-mgmt.default.svc.cluster.local:6222
        image: brobridgehub/nats-server:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8222
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 10

        ports:
        - containerPort: 4222
          name: nats
          protocol: TCP
        - containerPort: 6222
          name: nats-mgmt
          protocol: TCP
        - containerPort: 8222
          name: nats-http
          protocol: TCP
