name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout stage
      uses: actions/checkout@v2

    - name: build and publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./build/docker/Dockerfile
        name: iamjhe/nats-server
        tags: latest

